apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: "https://103.185.52.45:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTnpFek9UQTRNRFF3SGhjTk1qWXdNakU0TURVd01EQTBXaGNOTXpZd01qRTJNRFV3TURBMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTnpFek9UQTRNRFF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTckpZTUNCdG9kU2lGZ2k1bkJ0YnNRaE4wcTRnSmRJQ2lzeGRwN2FGR00KcTVaWk5iQXpLbjNrd05hU2JmZ2sxL2xUQWFIWnFSUlI0czdqaEFIclhUMjZvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXdHdVk4YVZ2QzVURDZnaUdFQlNTCmRrK2loU2t3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnYld1Y1NkQUVsZ3orcmp2Z1hrU0hXTTRSQnlrQVo4VjQKWDBlTjhYZzdJMmNDSVFDZWRtR2pVMzVQaUtheVFnQS9NWHJMd2ZyL1pBeUU3eUJzWHo2bGN5VFZKZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
contexts:
- name: muyung-anak-telyu
  context:
    cluster: local
    namespace: muyung-anak-telyu
    user: muyung-anak-telyu-sa
current-context: muyung-anak-telyu
users:
- name: muyung-anak-telyu-sa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlFteFl2cGk1RkF5TEFkdDJYSC05UnVmUGJhYXJCU0pBNjNEcUZxcEtsdFUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtdXl1bmctYW5hay10ZWx5dSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJtdXl1bmctYW5hay10ZWx5dS1zYS10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJtdXl1bmctYW5hay10ZWx5dS1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjAyMWU0NzRkLWFmZjktNDc2Ny1hYzU1LTJhNDIwMDBkMGU3NiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDptdXl1bmctYW5hay10ZWx5dTptdXl1bmctYW5hay10ZWx5dS1zYSJ9.YSPLIuOStPy9os_rlUsEFUguKcbXnHQl044H57I9OHtfKo5E7JImB_8cINPPAUv1BTqqach72nsxKQtCITxhexWqZqNQqcV2wf_7DGLaGYc3snoyuWoobp22FWGUlwApYQtD0-ReSDPmUKqialBuBEJCbE1XnrsubS8Y0ToDdVeMBF1jxLlwENGJwoEg4AeIrpdIC8_QYJbiZsP57qezzP1a97C-AGJC2K19-gjG8yi6SRX9hPH16mA1nir5EKkow7b9Xzqd5KUbwWHH-e7vWNZALltumLdxGE9N2tE4S1-ZuQE-ZSXyFSrtkgJY86jgIDjkUdovB5j1EVlj1apnaQ
