import { describe, it, expect, vi, beforeEach } from 'vitest'

// Mock generateSnippets so tests don't hit Gemini for snippet pre-fill
vi.mock('../lib/generators/snippets', () => ({
  generateSnippets: vi.fn(),
}))

// Mock generateJSON (used for batch enrichment inside api-docs.ts)
vi.mock('../lib/gemini', () => ({
  generateJSON: vi.fn(),
}))

import { generateApiDocs } from '../lib/generators/api-docs'
import { generateSnippets } from '../lib/generators/snippets'
import { generateJSON } from '../lib/gemini'
import type { AnalyzedRoute, FeatureGroup } from '../lib/types'

const mockGenerateSnippets = vi.mocked(generateSnippets)
const mockGenerateJSON = vi.mocked(generateJSON)

// ─── Fixtures ────────────────────────────────────────────────────────────────

function makeRoute(
  id: string,
  method: AnalyzedRoute['method'],
  path: string,
  overrides: Partial<AnalyzedRoute> = {}
): AnalyzedRoute {
  return {
    id,
    method,
    path,
    status: 'documented',
    detectedIn: 'backend',
    fetchSnippet: `// fetch ${method} ${path}`,
    tsTypes: `interface ${method}${path.replace(/\//g, '').replace(/:/g, '')}Response { id: number; }`,
    description: `${method} ${path} endpoint`,
    ...overrides,
  }
}

const AUTH_FEATURE_ID = 'feature-auth'
const USER_FEATURE_ID = 'feature-users'

const mockRoutes: AnalyzedRoute[] = [
  makeRoute('r1', 'POST', '/api/auth/login'),
  makeRoute('r2', 'GET', '/api/auth/me'),
  makeRoute('r3', 'GET', '/api/users'),
  makeRoute('r4', 'GET', '/api/users/:id'),
  makeRoute('r5', 'DELETE', '/api/users/:id'),
]

const mockFeatures: FeatureGroup[] = [
  {
    id: AUTH_FEATURE_ID,
    name: 'Authentication',
    description: 'Handles user auth flows',
    routeIds: ['r1', 'r2'],
  },
  {
    id: USER_FEATURE_ID,
    name: 'User Management',
    description: 'CRUD operations for users',
    routeIds: ['r3', 'r4', 'r5'],
  },
]

function enrichmentResponse(routes: AnalyzedRoute[]) {
  return {
    results: routes.map((r) => ({
      routeKey: `${r.method.toUpperCase()}:${r.path}`,
      description: `Enriched description for ${r.method} ${r.path}.`,
      requestBodyExample: r.method === 'POST' ? '{"email":"test@example.com"}' : '',
      responseExample: '{"id":1}',
      errorCodes: [400, 401, 500],
    })),
  }
}

beforeEach(() => {
  vi.clearAllMocks()
  // Default: enrichment succeeds
  mockGenerateJSON.mockResolvedValue(enrichmentResponse(mockRoutes))
})

// ─── Task 3.2 — Markdown structure tests ────────────────────────────────────

describe('generateApiDocs — Markdown output', () => {
  it('contains the top-level heading and timestamp', async () => {
    const { markdown } = await generateApiDocs(mockRoutes, mockFeatures)
    expect(markdown).toContain('# API Documentation')
    expect(markdown).toMatch(/Generated by GAP/)
  })

  it('contains a Table of Contents with all feature names', async () => {
    const { markdown } = await generateApiDocs(mockRoutes, mockFeatures)
    expect(markdown).toContain('## Table of Contents')
    expect(markdown).toContain('Authentication')
    expect(markdown).toContain('User Management')
  })

  it('contains feature section headings', async () => {
    const { markdown } = await generateApiDocs(mockRoutes, mockFeatures)
    expect(markdown).toContain('## Authentication')
    expect(markdown).toContain('## User Management')
  })

  it('contains per-route subsections with METHOD and path', async () => {
    const { markdown } = await generateApiDocs(mockRoutes, mockFeatures)
    expect(markdown).toContain('### `POST /api/auth/login`')
    expect(markdown).toContain('### `GET /api/auth/me`')
    expect(markdown).toContain('### `DELETE /api/users/:id`')
  })

  it('includes --- separators between routes', async () => {
    const { markdown } = await generateApiDocs(mockRoutes, mockFeatures)
    expect(markdown).toContain('---')
  })

  it('includes enriched descriptions for routes', async () => {
    const { markdown } = await generateApiDocs(mockRoutes, mockFeatures)
    expect(markdown).toContain('Enriched description for POST /api/auth/login')
  })

  it('does not call generateSnippets when routes already have snippets', async () => {
    await generateApiDocs(mockRoutes, mockFeatures)
    expect(mockGenerateSnippets).not.toHaveBeenCalled()
  })

  it('calls generateSnippets for routes missing fetchSnippet', async () => {
    const incomplete: AnalyzedRoute[] = [
      makeRoute('r1', 'GET', '/api/health', { fetchSnippet: undefined, tsTypes: undefined }),
    ]
    const features: FeatureGroup[] = [{ id: 'f1', name: 'Health', routeIds: ['r1'] }]
    mockGenerateSnippets.mockResolvedValue({
      fetchSnippet: '// health fetch',
      tsTypes: 'interface HealthResponse { status: string; }',
      description: 'Health endpoint',
    })
    mockGenerateJSON.mockResolvedValue(enrichmentResponse(incomplete))

    await generateApiDocs(incomplete, features)
    expect(mockGenerateSnippets).toHaveBeenCalledOnce()
  })
})

// ─── Task 3.3 — OpenAPI output tests ─────────────────────────────────────────

describe('generateApiDocs — OpenAPI output', () => {
  it('has openapi version 3.0.0', async () => {
    const { openapi } = await generateApiDocs(mockRoutes, mockFeatures)
    const doc = openapi as Record<string, unknown>
    expect(doc.openapi).toBe('3.0.0')
  })

  it('has correct info object', async () => {
    const { openapi } = await generateApiDocs(mockRoutes, mockFeatures)
    const doc = openapi as { info: { title: string; version: string } }
    expect(doc.info.title).toBe('GAP Generated API')
    expect(doc.info.version).toBe('1.0.0')
  })

  it('has paths for all routes', async () => {
    const { openapi } = await generateApiDocs(mockRoutes, mockFeatures)
    const paths = (openapi as { paths: Record<string, unknown> }).paths
    expect(paths['/api/auth/login']).toBeDefined()
    expect(paths['/api/auth/me']).toBeDefined()
    expect(paths['/api/users']).toBeDefined()
    expect(paths['/api/users/{id}']).toBeDefined()
  })

  it('POST routes have requestBody', async () => {
    const { openapi } = await generateApiDocs(mockRoutes, mockFeatures)
    const paths = (openapi as { paths: Record<string, Record<string, { requestBody?: unknown }>> }).paths
    expect(paths['/api/auth/login']['post'].requestBody).toBeDefined()
  })

  it('GET routes do not have requestBody', async () => {
    const { openapi } = await generateApiDocs(mockRoutes, mockFeatures)
    const paths = (openapi as { paths: Record<string, Record<string, { requestBody?: unknown }>> }).paths
    expect(paths['/api/auth/me']['get'].requestBody).toBeUndefined()
  })

  it('each route has responses object', async () => {
    const { openapi } = await generateApiDocs(mockRoutes, mockFeatures)
    const paths = (openapi as {
      paths: Record<string, Record<string, { responses: Record<string, unknown> }>>
    }).paths
    const loginOp = paths['/api/auth/login']['post']
    expect(loginOp.responses['200']).toBeDefined()
    expect(loginOp.responses['400']).toBeDefined()
  })

  it('has components.schemas populated from tsTypes', async () => {
    const { openapi } = await generateApiDocs(mockRoutes, mockFeatures)
    const doc = openapi as { components: { schemas: Record<string, unknown> } }
    expect(Object.keys(doc.components.schemas).length).toBeGreaterThan(0)
  })
})

// ─── Task 3.4 — Enrichment fallback tests ────────────────────────────────────

describe('generateApiDocs — enrichment fallback', () => {
  it('resolves without throwing when Gemini enrichment fails', async () => {
    mockGenerateJSON.mockRejectedValue(new Error('Gemini quota exceeded'))
    await expect(generateApiDocs(mockRoutes, mockFeatures)).resolves.toBeDefined()
  })

  it('uses fallback description when enrichment fails', async () => {
    mockGenerateJSON.mockRejectedValue(new Error('Network error'))
    const { markdown } = await generateApiDocs(mockRoutes, mockFeatures)
    expect(markdown).toContain('# API Documentation')
    // fallback descriptions contain method+path
    expect(markdown).toContain('POST /api/auth/login')
  })

  it('returns valid OpenAPI even when enrichment fails', async () => {
    mockGenerateJSON.mockRejectedValue(new Error('timeout'))
    const { openapi } = await generateApiDocs(mockRoutes, mockFeatures)
    const doc = openapi as Record<string, unknown>
    expect(doc.openapi).toBe('3.0.0')
    expect(doc.paths).toBeDefined()
  })
})

// ─── Task 3.5 — Empty routes tests ───────────────────────────────────────────

describe('generateApiDocs — empty routes', () => {
  it('returns Markdown with "no routes" message for empty input', async () => {
    const { markdown } = await generateApiDocs([], [])
    expect(markdown).toContain('# API Documentation')
    expect(markdown).toContain('No routes were found')
  })

  it('returns openapi.paths as empty object for empty input', async () => {
    const { openapi } = await generateApiDocs([], [])
    const doc = openapi as { paths: Record<string, unknown> }
    expect(doc.paths).toEqual({})
  })

  it('does not call Gemini for empty input', async () => {
    await generateApiDocs([], [])
    expect(mockGenerateJSON).not.toHaveBeenCalled()
    expect(mockGenerateSnippets).not.toHaveBeenCalled()
  })
})
