import { generateJSON } from '../ai-provider'
import { generateSnippets } from './snippets'
import type { AnalyzedRoute, FeatureGroup } from '../types'

// ─── Enrichment types ────────────────────────────────────────────────────────

interface RouteEnrichment {
  routeKey: string
  description: string
  requestBodyExample: string
  responseExample: string
  errorCodes: number[]
}

interface EnrichmentResponse {
  results: RouteEnrichment[]
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

const WRITE_METHODS = new Set(['POST', 'PUT', 'PATCH'])
const BATCH_SIZE = 20

function routeKey(r: AnalyzedRoute): string {
  return `${r.method.toUpperCase()}:${r.path}`
}

// ─── Task 1.2 — snippet pre-fill ─────────────────────────────────────────────

async function prefillSnippets(routes: AnalyzedRoute[]): Promise<AnalyzedRoute[]> {
  const result: AnalyzedRoute[] = []
  for (const route of routes) {
    if (route.fetchSnippet && route.tsTypes) {
      result.push(route)
      continue
    }
    try {
      const snippets = await generateSnippets(route)
      result.push({
        ...route,
        fetchSnippet: route.fetchSnippet ?? snippets.fetchSnippet,
        tsTypes: route.tsTypes ?? snippets.tsTypes,
        description: route.description ?? snippets.description,
      })
    } catch {
      result.push(route)
    }
  }
  return result
}

// ─── Task 1.3 + 1.4 — Gemini batch enrichment with retry ────────────────────

const ENRICHMENT_SCHEMA = {
  type: 'object',
  properties: {
    results: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          routeKey: { type: 'string' },
          description: { type: 'string' },
          requestBodyExample: { type: 'string' },
          responseExample: { type: 'string' },
          errorCodes: { type: 'array', items: { type: 'number' } },
        },
        required: ['routeKey', 'description', 'requestBodyExample', 'responseExample', 'errorCodes'],
      },
    },
  },
  required: ['results'],
}

function buildEnrichmentPrompt(routes: AnalyzedRoute[]): string {
  const list = routes
    .map((r) => `- ${r.method} ${r.path}${r.description ? ` // ${r.description}` : ''}`)
    .join('\n')

  return `You are an API documentation expert. For each route below, provide enriched documentation.

Routes:
${list}

For each route return:
- routeKey: "METHOD:/path" (exact match)
- description: 2-3 sentences explaining what the endpoint does, its purpose, and any important behavior
- requestBodyExample: JSON string of a realistic request body (empty string "" for GET/DELETE routes)
- responseExample: JSON string of a realistic successful response
- errorCodes: array of relevant HTTP error codes the endpoint may return (e.g. [400, 401, 404, 500])

Respond only with JSON.`
}

async function enrichRoutesBatch(routes: AnalyzedRoute[]): Promise<Map<string, RouteEnrichment>> {
  const result = new Map<string, RouteEnrichment>()

  const chunks: AnalyzedRoute[][] = []
  for (let i = 0; i < routes.length; i += BATCH_SIZE) {
    chunks.push(routes.slice(i, i + BATCH_SIZE))
  }

  for (const chunk of chunks) {
    let raw: EnrichmentResponse
    try {
      raw = await generateJSON<EnrichmentResponse>(buildEnrichmentPrompt(chunk), ENRICHMENT_SCHEMA)
    } catch {
      // fallback for entire chunk
      for (const r of chunk) {
        result.set(routeKey(r), {
          routeKey: routeKey(r),
          description: `${r.method} ${r.path} endpoint`,
          requestBodyExample: '',
          responseExample: '',
          errorCodes: [400, 500],
        })
      }
      continue
    }

    const byKey = new Map<string, RouteEnrichment>()
    for (const entry of raw.results ?? []) {
      if (entry.routeKey) byKey.set(entry.routeKey, entry)
    }

    for (const r of chunk) {
      const key = routeKey(r)
      const enrichment = byKey.get(key) ?? {
        routeKey: key,
        description: `${r.method} ${r.path} endpoint`,
        requestBodyExample: '',
        responseExample: '',
        errorCodes: [400, 500],
      }
      result.set(key, enrichment)
    }
  }

  return result
}

// ─── Task 1.5 — Markdown builder ─────────────────────────────────────────────

function buildMarkdown(
  routes: AnalyzedRoute[],
  features: FeatureGroup[],
  enrichment: Map<string, RouteEnrichment>
): string {
  const routeById = new Map(routes.map((r) => [r.id, r]))
  const timestamp = new Date().toISOString()
  const lines: string[] = []

  if (routes.length === 0) {
    return `# API Documentation\n\n_Generated by GAP — ${timestamp}_\n\nNo routes were found in the provided code.\n`
  }

  lines.push(`# API Documentation`)
  lines.push(``)
  lines.push(`_Generated by GAP — ${timestamp}_`)
  lines.push(``)

  // Table of Contents
  lines.push(`## Table of Contents`)
  lines.push(``)
  for (const feature of features) {
    const anchor = feature.name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')
    lines.push(`- [${feature.name}](#${anchor})`)
  }
  lines.push(``)

  // Feature sections
  for (const feature of features) {
    lines.push(`## ${feature.name}`)
    lines.push(``)
    if (feature.description) {
      lines.push(`_${feature.description}_`)
      lines.push(``)
    }

    const featureRoutes = feature.routeIds
      .map((id) => routeById.get(id))
      .filter((r): r is AnalyzedRoute => r !== undefined)

    for (const route of featureRoutes) {
      const rk = routeKey(route)
      const enrich = enrichment.get(rk)
      const description = enrich?.description ?? route.description ?? `${route.method} ${route.path} endpoint`
      const isWrite = WRITE_METHODS.has(route.method.toUpperCase())

      lines.push(`### \`${route.method} ${route.path}\``)
      lines.push(``)
      lines.push(description)
      lines.push(``)

      if (isWrite && enrich?.requestBodyExample) {
        lines.push(`**Request:**`)
        lines.push(`\`\`\`typescript`)
        lines.push(route.tsTypes ? extractRequestType(route.tsTypes) : enrich.requestBodyExample)
        lines.push(`\`\`\``)
        lines.push(``)
      }

      if (route.tsTypes) {
        lines.push(`**Response:**`)
        lines.push(`\`\`\`typescript`)
        lines.push(extractResponseType(route.tsTypes))
        lines.push(`\`\`\``)
        lines.push(``)
      } else if (enrich?.responseExample) {
        lines.push(`**Response:**`)
        lines.push(`\`\`\`json`)
        lines.push(enrich.responseExample)
        lines.push(`\`\`\``)
        lines.push(``)
      }

      if (route.fetchSnippet) {
        lines.push(`**Example:**`)
        lines.push(`\`\`\`typescript`)
        lines.push(route.fetchSnippet)
        lines.push(`\`\`\``)
        lines.push(``)
      }

      if (enrich?.errorCodes && enrich.errorCodes.length > 0) {
        lines.push(`**Error codes:** ${enrich.errorCodes.join(', ')}`)
        lines.push(``)
      }

      lines.push(`---`)
      lines.push(``)
    }
  }

  return lines.join('\n')
}

// ─── Task 1.6 — OpenAPI 3.0 builder ──────────────────────────────────────────

interface OpenAPISchema {
  type?: string
  properties?: Record<string, OpenAPISchema>
  items?: OpenAPISchema
  description?: string
  $ref?: string
}

interface OpenAPIPath {
  [method: string]: {
    summary: string
    description: string
    tags: string[]
    requestBody?: {
      required: boolean
      content: { 'application/json': { schema: OpenAPISchema } }
    }
    responses: {
      '200': { description: string; content?: { 'application/json': { schema: OpenAPISchema } } }
      [code: string]: { description: string; content?: unknown }
    }
  }
}

function tsTypesToSchema(tsTypes: string, preferRequest: boolean): OpenAPISchema {
  if (!tsTypes) return { type: 'object' }

  const target = preferRequest ? 'Request' : 'Response'
  const interfaceRegex = /interface\s+(\w*(?:Request|Response)\w*)\s*\{([^}]*)\}/g
  const allInterfaces: Array<{ name: string; body: string }> = []
  let match: RegExpExecArray | null

  while ((match = interfaceRegex.exec(tsTypes)) !== null) {
    allInterfaces.push({ name: match[1], body: match[2] })
  }

  const chosen =
    allInterfaces.find((i) => i.name.includes(target)) ??
    allInterfaces[0]

  if (!chosen) return { type: 'object', description: 'See TypeScript type' }

  const properties: Record<string, OpenAPISchema> = {}
  const propRegex = /(\w+)\??:\s*([^;\n]+)/g
  let pm: RegExpExecArray | null

  while ((pm = propRegex.exec(chosen.body)) !== null) {
    const propName = pm[1]
    const propType = pm[2].trim()
    properties[propName] = tsTypeToSchema(propType)
  }

  return { type: 'object', properties }
}

function tsTypeToSchema(tsType: string): OpenAPISchema {
  const t = tsType.replace(/;$/, '').trim()
  if (t === 'string') return { type: 'string' }
  if (t === 'number' || t === 'int' || t === 'integer') return { type: 'number' }
  if (t === 'boolean') return { type: 'boolean' }
  if (t.endsWith('[]')) return { type: 'array', items: tsTypeToSchema(t.slice(0, -2)) }
  if (t.startsWith('Array<')) return { type: 'array', items: tsTypeToSchema(t.slice(6, -1)) }
  return { type: 'object' }
}

function extractRequestType(tsTypes: string): string {
  const match = tsTypes.match(/interface\s+\w*Request\w*\s*\{[^}]*\}/)
  return match ? match[0] : tsTypes
}

function extractResponseType(tsTypes: string): string {
  const match = tsTypes.match(/interface\s+\w*Response\w*\s*\{[^}]*\}/)
  return match ? match[0] : tsTypes
}

function buildOpenAPI(
  routes: AnalyzedRoute[],
  features: FeatureGroup[],
  enrichment: Map<string, RouteEnrichment>
): object {
  const featureByRouteId = new Map<string, string>()
  for (const f of features) {
    for (const rid of f.routeIds) {
      featureByRouteId.set(rid, f.name)
    }
  }

  const paths: Record<string, OpenAPIPath> = {}
  const schemas: Record<string, OpenAPISchema> = {}

  for (const route of routes) {
    const rk = routeKey(route)
    const enrich = enrichment.get(rk)
    const method = route.method.toLowerCase()
    const tag = featureByRouteId.get(route.id) ?? 'General'
    const isWrite = WRITE_METHODS.has(route.method.toUpperCase())
    const description = enrich?.description ?? route.description ?? `${route.method} ${route.path} endpoint`

    // Convert Express :param → OpenAPI {param}
    const openApiPath = route.path.replace(/:([^/]+)/g, '{$1}')

    if (!paths[openApiPath]) paths[openApiPath] = {} as OpenAPIPath

    const responseSchema = route.tsTypes
      ? tsTypesToSchema(route.tsTypes, false)
      : { type: 'object' }

    const operation: OpenAPIPath[string] = {
      summary: `${route.method} ${route.path}`,
      description,
      tags: [tag],
      responses: {
        '200': {
          description: 'Success',
          content: { 'application/json': { schema: responseSchema } },
        },
        '400': { description: 'Bad Request' },
        '401': { description: 'Unauthorized' },
        '500': { description: 'Internal Server Error' },
      },
    }

    if (isWrite) {
      const requestSchema = route.tsTypes
        ? tsTypesToSchema(route.tsTypes, true)
        : { type: 'object' }
      operation.requestBody = {
        required: true,
        content: { 'application/json': { schema: requestSchema } },
      }
    }

    paths[openApiPath][method] = operation

    // Populate schemas from tsTypes
    if (route.tsTypes) {
      const interfaceRegex = /interface\s+(\w+)\s*\{([^}]*)\}/g
      let m: RegExpExecArray | null
      while ((m = interfaceRegex.exec(route.tsTypes)) !== null) {
        const schemaName = m[1]
        if (!schemas[schemaName]) {
          schemas[schemaName] = tsTypesToSchema(route.tsTypes, schemaName.includes('Request'))
        }
      }
    }
  }

  return {
    openapi: '3.0.0',
    info: {
      title: 'GAP Generated API',
      version: '1.0.0',
      description: 'Auto-generated by GAP — API Intelligence Platform',
    },
    paths,
    components: { schemas },
  }
}

// ─── Public API ───────────────────────────────────────────────────────────────

export async function generateApiDocs(
  routes: AnalyzedRoute[],
  features: FeatureGroup[]
): Promise<{ markdown: string; openapi: object }> {
  if (routes.length === 0) {
    return {
      markdown: `# API Documentation\n\n_Generated by GAP — ${new Date().toISOString()}_\n\nNo routes were found in the provided code.\n`,
      openapi: {
        openapi: '3.0.0',
        info: { title: 'GAP Generated API', version: '1.0.0' },
        paths: {},
        components: { schemas: {} },
      },
    }
  }

  // Phase 1: ensure all routes have fetchSnippet + tsTypes
  const enrichedRoutes = await prefillSnippets(routes)

  // Phase 2: batch-enrich with Gemini for richer doc data
  const enrichment = await enrichRoutesBatch(enrichedRoutes)

  const markdown = buildMarkdown(enrichedRoutes, features, enrichment)
  const openapi = buildOpenAPI(enrichedRoutes, features, enrichment)

  return { markdown, openapi }
}
